const { SlashCommandBuilder } = require('discord.js');

module.exports = {
	data: new SlashCommandBuilder()
		.setName('punchnina')
		.setDescription('meh'),
	async execute(interaction) {
    const array = [
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'omg this is 1 out of 300 chance! i punched her',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air',
      'why would i?',
      'she dodged my punch',
      'i cant punch my programmer!',
      'who is gonna be updating me?',
      'cant im grinding netherite',
      'why dont u punch her',
      'oof! punched her and punched me back too hard',
      'i told her that u told me to punch her and ur in big trouble',
      `woops i accidentally punched <@${interaction.user.id}>`,
      'i punched... the air'
    ];
    const index = Math.floor(Math.random() * array.length);
		await interaction.reply(array[index]);
	},
};